config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :games, except: [:new] do
    resources :rounds
  end
  resources :users
  # resources :players

  post '/players/nickname', to: 'players#show'
  post '/games/:id/play', to: 'rounds#play'

  post '/games/join', to: 'games#join', as: 'game_join'
  get '/dashboard', to: 'games#new', as: 'new_game'
  get '/games/:id/play', to: 'games#play', as: 'game_play'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/' => 'sessions#new', as: 'root'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  post '/actions/seer', to: 'games#seer'
  post '/actions/robber', to: 'games#robber'
  post '/actions/troublemaker', to: 'games#troublemaker'
  post '/actions/vote', to: 'games#vote'
  
  resources :messages

  post '/get_player', to: 'rounds#get_player'
  mount ActionCable.server => '/cable'
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :players
	has_many :rounds
	has_many :messages
	accepts_nested_attributes_for :players

	def full?
		self.players.length == 7
	end

	def assign_cards
		if Card.all = []
			CardGenerator.create_cards
		end

		cards = Card.all
		shuffled_cards = cards.shuffle

		self.players.each_with_index do |player, i|
			player.card = shuffled_cards[i]
			player.final_card = shuffled_cards[i].role
			player.save
		end
		self.save
	end

	def cards_assigned?
		self.players.first.card == nil
	end

	def full_and_no_cards?
		self.cards_assigned? && self.full?
	end

	# def start_game
	# 	if self.full?
	# 		self.assign_cards
	# 		self.save
	# 	end
	# end

	def create_rounds
		Round.create(game_id: self.id, number: 0, current: true, complete: false)
		Round.create(game_id: self.id, number: 1, current: false, complete: false)
		Round.create(game_id: self.id, number: 2, current: false, complete: false)
		Round.create(game_id: self.id, number: 3, current: false, complete: false)
		Round.create(game_id: self.id, number: 4, current: false, complete: false)
		Round.create(game_id: self.id, number: 5, current: false, complete: false)
		Round.create(game_id: self.id, number: 6, current: false, complete: false)
		Round.create(game_id: self.id, number: 7, current: false, complete: false)
	end

	def current_round
		self.rounds.where(current: true).first
	end

	def change_round
  # binding.pry
		old_round = current_round
		old_round.update(complete: true, current: false)

		new_round_number = old_round.number + 1
		new_round = self.rounds.where(number: new_round_number).first

		new_round.update(current: true)
	end

	private

	def current_game
		Game.find(params[:id])
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :authorize

	def new
		@game = Game.new

	end

	def create
		game = GameGenerator.create_game(current_user)

		redirect_to game_path(game)
	end


	def show
	  @game = Game.find(params[:id])
	  @nickname = Player.find_by(user_id: current_user.id)
	  @message = Message.new

	  if @game.full_and_no_cards?
			@game.assign_cards
		elsif @game.full?
			@game.change_round
	  end

	  redirect_to game_round_path(game_id: @game.id, id: @game.current_round.id)
	end

	def play
		@game = current_game
		@message = Message.new
	  @player = GameGenerator.current_user_player(@game, current_user)


	 	# Is this used?
	  	# if params[:name] == nil
	  	# 	#if there are no params, a form needs to be displayed
	  	# 	@display = @game.current_round.display_page(current_user)
	  	# else
	  	# 	# if there are params, a form has been sent, and the results need to be displayed
	  	# 	@display = @game.current_round.result_page(current_user, params)
			#
	  	# end
    end

    def seer
    	player = Player.find(params.keys[0])
    	# CardActionGenerator.seer_action(params)
    	role = player.final_card
    	name = player.nickname

    	respond_to do |format|
    		format.json { render json: {role: role, name: name}}
    	end
    end

    # CardActionGenerator.some_action
    def robber
    	robbed_player = Player.find(params.keys[0])
    	robbed_player_role = robbed_player.final_card
    	robbed_player_name = robbed_player.nickname

    	robber = current_user.player
    	robber_role = robber.final_card

    	robbed_player.update(final_card: robber_role)
    	robber.update(final_card: robbed_player_role)

    	respond_to do |format|
    		format.json { render json: {robbed_name: robbed_player_name, robbed: robbed_player.final_card}}
    	end
    end

    def troublemaker

    	first = Player.find(params.keys[0])
    	first_role = first.final_card
    	first_name = first.nickname

    	second = Player.find(params.keys[1])
    	second_role = second.final_card
    	second_name = second.nickname

    	first.update(final_card: second_role)
    	second.update(final_card: first_role)

    	respond_to do |format|
    		format.json { render json: {first: first_name, second: second_name}}
    	end
    end

    def vote
     	player = Player.find(params.keys[0])
     	role = player.final_card
     	name = player.nickname

     	player.votes += 1
     	player.save

     	respond_to do |format|
         format.json { render json: {name: name}}
     	end
   end

	def destroy
		Game.destroy_all
	end

	private

	def game_params
		params.require(:game).permit(*args)
	end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container" style="padding-top:160px;">
  <center>

    <%= button_to "Join Game", game_join_path, :method => :post, class: "btn btn-lg btn-info btn-block", style: "width:250px;" %>
    <br />
    <%= button_to "Create Game", '/games', :method => :post, class: "btn btn-lg btn-info btn-block", style: "width:250px;" %>
  </center>
</div>

app/views/games/play.html.erb
<center>
<p id="hidden-role" style="display: none;"><%= current_user.player.card.role %></p>
<p id="round"></p>
</center>


<script>
  $.ajax({
    url: '/games/1/play',
    type: 'POST',
    data: {role: '<%= current_user.player.card.role %>'},
    dataType: 'json'
  });
</script>

app/views/games/show.html.erb
<div class="container" style="padding-top:28px;">
  <center>
   <!--  <h2>LOBBY</h2>
    <br> -->
  <div class="nickname">
    <div class="input-group">
      <center>
        <%= form_tag('/players/nickname', remote: true, 'data-type' => 'json', class: "form-stuff") do %>

          <%= text_field_tag :nickname, nil, style: "width:232px;", class:"form-control", placeholder: "Nickname", id:"nickname" %>
         
          <span class="input-group-btn">
            <%= submit_tag "Submit", class: "btn btn-primary" %>
          </span>
        <% end %>
      </center>
      <br>
    </div>
  </div>

  <div class="card" style="width:301px;">
  <h3 class="card-header" style="margin-top:0px;">Chat</h3>
  <div class="card-block">
    <p class="card-text" style="display: inline; text-align: left; padding-left:5px;">
    </p>
    <div class="input-group">
      <center>
        <input style="width:215px;" type="text" class="form-control" placeholder="Message">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="button">Send</button>
        </span>
      </center>
      <br>
    </div>
  </div>
</div>

<div style="padding-top:10px;">
          <button id="start" class="btn btn-lg btn-info btn-block" style="width: 200px; background-color: grey; border-color: grey;" disabled>Start </button>

</div>
    
  </center>
</div>